@startuml

hide empty members

package social {

package action {

class Action {
  int calculateUtility(Context context)
  Update execute(Context context)
}

enum Role {
  SPEAKER
  TARGET
  OBSERVER
}

class Context {
  Action action
  Map<Role,Character> roles
}

class Update {
  Context context
  Map<CharacterId,Character> updatedCharacters
}

}

package utils {

package effect {

interface Effect {
  Update applyTo(Update update)
}

}

package utility {

class UtilityRule {
  String description
  int modifier
  int getUtilityModifier(Context context)
}

}

package condition {

interface Condition {
  bool evaluate(Context context)
}

}

}

}

Action "1" *-- "*" UtilityRule
Action "1" *-- "*" Effect
Action -[hidden]- Update
UtilityRule "1" *-- "*" Condition

Context -- Role


@enduml