@startuml

hide empty members

package character {

package attitude {

class AttitudeType {
  String name
  int default
}

class AttitudeComponent {
  Map<Pair<CharacterId,AttitudeType>,Int> attitudes
  Map<AttitudeType,Int> getAttitudes(CharacterId id)
  Map<CharacterId,Int> getAttitudes(AttitudeType type)
  int getAttitude(CharacterId id, AttitudeType type)
}

}

class CharacterId

class Character

}

AttitudeComponent --  AttitudeType
Character *--  AttitudeComponent
CharacterId *--  Character

@enduml