@startuml

hide empty members

package social.utils.condition {

interface Condition {
  bool evaluate(Context context)
}

class AttitudeCondition {
  Role from, toward
  AttitudeType type
  int threshold
  bool checkForBigger
}

class CauseEmotionCondition {
  Role role
  EmotionType type
}

class HasEmotion {
  Role role
  EmotionType type
}

class HasRelationship {
  Role from, toward
  Relationship relationship
}

}

Condition <|-- AttitudeCondition
Condition <|-- CauseEmotionCondition
Condition <|-- HasEmotion
Condition <|-- HasRelationship


@enduml