@startuml

hide empty members

package social {

package effect {

interface Effect {
  Update applyTo(Update update)
}

class CauseEmotion {
  Role role
  Emotion emotion
}

class ModifyAttitude {
  Role from, toward
  AttitudeType type
  int value
}

}

}

Effect <|-- CauseEmotion
Effect <|-- ModifyAttitude


@enduml