@startuml

hide empty members

package character {

package emotion {

class EmotionType {
  String name
  bool isPositive
}

class Emotion {
  int strength
  int duration
}

class Mood {
  List<Emotion> getAllEmotions()
  Emotion getDominantEmotion()
}

}

class Character

}

Emotion *--  EmotionType
Mood "1" *-- "*"  Emotion
Character *--  Mood

@enduml