@startuml

hide empty members

package character {

package trait {

class Trait {
  String name
}

class TraitComponent {
  bool hasTrait(Trait trait)
}

}


class Character

}

TraitComponent "1" *-- "*"  Trait
Character *--  TraitComponent

@enduml